[legacy_rigs]
Ariadne ansible_host=10.21.17.49 ansible_user=pi
Hingle ansible_host=10.21.17.13 ansible_user=pi
Breezy ansible_host=10.21.17.61 ansible_user=pi
OG ansible_host=10.21.17.30 ansible_user=pi
NoName2 ansible_host=10.21.17.65 ansible_user=pi
GumDrop ansible_host=10.21.17.5 ansible_user=pi
Excalibur ansible_host=10.21.17.53 ansible_user=pi
Aphrodite ansible_host=10.21.17.72 ansible_user=pi
Trickster ansible_host=10.21.17.79 ansible_user=pi

[legacy_rigs:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args="-o StrictHostKeyChecking=no"
